/// <reference types="@cloudflare/workers-types" />

// Generated by Wrangler by running `wrangler types`

interface Env {
	DB: D1Database;
	CACHE: KVNamespace;
	ALERT_STORE: DurableObjectNamespace;
}