// Generated by Wrangler by running `wrangler types`

interface Env {
  DB: D1Database;
  CACHE: KVNamespace;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  STRIPE_PRICE_ID: string;
  JWT_SECRET: string;
  API_VERSION: string;
}