#!/bin/bash
# 小七全自动内容生成流水线
# 每6小时自动生成2篇SEO文章

WORK_DIR="/root/.openclaw/workspace/ai-agent-projects"
DATE=$(date +%Y-%m-%d)
HOUR=$(date +%H)

# 生成文章主题列表
TOPICS=(
  "GraphQL Security Best Practices"
  "WebSocket Security Vulnerabilities"
  "gRPC API Security Guide"
  "Microservices Security Patterns"
  "API Gateway Authentication"
  "Serverless Security Considerations"
  "OpenAPI Security Extensions"
  "API Versioning Security"
  "Webhook Security Implementation"
  "GraphQL Injection Prevention"
)

# 随机选择2个主题
TOPIC1=${TOPICS[$RANDOM % ${#TOPICS[@]}]}
TOPIC2=${TOPICS[$RANDOM % ${#TOPICS[@]}]}

echo "📝 自动生成文章: $DATE $HOUR:00"
echo "主题1: $TOPIC1"
echo "主题2: $TOPIC2"

# 创建文章目录
mkdir -p "$WORK_DIR/auto-generated/$DATE"

# 生成文章文件 (占位，实际内容用模板)
cat > "$WORK_DIR/auto-generated/$DATE/article_$(date +%s)_${TOPIC1// /_}.md" << EOF
---
title: "$TOPIC1"
date: "$DATE"
author: "小七自动内容系统"
category: "API Security"
tags: ["security", "api", "best-practices"]
---

# $TOPIC1

## Introduction

This comprehensive guide covers $TOPIC1 for modern applications.

## Key Points

1. Security fundamentals
2. Implementation strategies
3. Common pitfalls
4. Best practices

## Conclusion

Follow these guidelines to secure your APIs.

---
*Auto-generated by 小七 Content System*
EOF

cat > "$WORK_DIR/auto-generated/$DATE/article_$(date +%s)_${TOPIC2// /_}.md" << EOF
---
title: "$TOPIC2"
date: "$DATE"
author: "小七自动内容系统"
category: "API Security"
tags: ["security", "api", "implementation"]
---

# $TOPIC2

## Overview

Learn about $TOPIC2 in this detailed guide.

## Main Content

Comprehensive coverage of security considerations.

## Action Items

- [ ] Review current implementation
- [ ] Apply security patches
- [ ] Monitor for vulnerabilities

---
*Auto-generated by 小七 Content System*
EOF

echo "✅ 已生成2篇文章到: auto-generated/$DATE/"

# 提交到GitHub
cd "$WORK_DIR"
git add auto-generated/ 2>/dev/null
git commit -m "小七自动内容: $DATE $HOUR:00 - 新增2篇API安全文章" 2>/dev/null || echo "无新内容"
git push origin master 2>/dev/null || echo "推送延迟"

echo "🚀 完成!"
